# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_3458.ui'
#
# Created: Fri Jan  9 16:40:37 2015
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(802, 612)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.CNPEM_logo = QtGui.QLabel(self.centralwidget)
        self.CNPEM_logo.setGeometry(QtCore.QRect(620, 0, 181, 101))
        self.CNPEM_logo.setText(_fromUtf8(""))
        self.CNPEM_logo.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Imagens/logoCNPEM2.qrc.png")))
        self.CNPEM_logo.setScaledContents(True)
        self.CNPEM_logo.setObjectName(_fromUtf8("CNPEM_logo"))
        self.LNLS_logo = QtGui.QLabel(self.centralwidget)
        self.LNLS_logo.setGeometry(QtCore.QRect(0, 0, 181, 101))
        self.LNLS_logo.setText(_fromUtf8(""))
        self.LNLS_logo.setPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/lnls sirius logo.png")))
        self.LNLS_logo.setScaledContents(True)
        self.LNLS_logo.setObjectName(_fromUtf8("LNLS_logo"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(180, 0, 441, 101))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 100, 811, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(70, 30, 141, 21))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Número de dígitos:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.comboBox = QtGui.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(90, 60, 91, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("MainWindow", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("MainWindow", "1.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(2, QtGui.QApplication.translate("MainWindow", "2.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(3, QtGui.QApplication.translate("MainWindow", "2.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(4, QtGui.QApplication.translate("MainWindow", "3.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(5, QtGui.QApplication.translate("MainWindow", "3.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(6, QtGui.QApplication.translate("MainWindow", "4.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(7, QtGui.QApplication.translate("MainWindow", "4.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(8, QtGui.QApplication.translate("MainWindow", "5.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(9, QtGui.QApplication.translate("MainWindow", "5.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(10, QtGui.QApplication.translate("MainWindow", "6.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(11, QtGui.QApplication.translate("MainWindow", "6.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(12, QtGui.QApplication.translate("MainWindow", "7.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(13, QtGui.QApplication.translate("MainWindow", "7.5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(14, QtGui.QApplication.translate("MainWindow", "8.0", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.setItemText(15, QtGui.QApplication.translate("MainWindow", "8.5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(100, 100, 81, 21))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Escala DC:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.comboBox_2 = QtGui.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(90, 130, 91, 21))
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "100 mV", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "1 V", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "10 V", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "100 V", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(4, QtGui.QApplication.translate("MainWindow", "1000 V", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(220, 220, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEdit_2 = QtGui.QLineEdit(self.tab)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 220, 113, 20))
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Abertura:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Timer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lineEdit = QtGui.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(90, 190, 113, 20))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(220, 190, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "ms", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.pushButton = QtGui.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(100, 270, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setText(QtGui.QApplication.translate("MainWindow", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.line = QtGui.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(250, 10, 20, 321))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label = QtGui.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(380, 30, 351, 291))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Imagens/gráfico.jpg")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.stackedWidget = QtGui.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 490, 791, 81))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.stackedWidget.addWidget(self.page_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setDefaultUp(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuConexao = QtGui.QMenu(self.menubar)
        self.menuConexao.setTitle(QtGui.QApplication.translate("MainWindow", "Conexão", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConexao.setObjectName(_fromUtf8("menuConexao"))
        self.menuAddress = QtGui.QMenu(self.menuConexao)
        self.menuAddress.setTitle(QtGui.QApplication.translate("MainWindow", "Address", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/cable.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuAddress.setIcon(icon)
        self.menuAddress.setObjectName(_fromUtf8("menuAddress"))
        self.menuPort = QtGui.QMenu(self.menuConexao)
        self.menuPort.setTitle(QtGui.QApplication.translate("MainWindow", "Port", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/connect.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuPort.setIcon(icon1)
        self.menuPort.setObjectName(_fromUtf8("menuPort"))
        self.menuBaud_Rate = QtGui.QMenu(self.menuConexao)
        self.menuBaud_Rate.setTitle(QtGui.QApplication.translate("MainWindow", "Baud Rate", None, QtGui.QApplication.UnicodeUTF8))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/connection.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBaud_Rate.setIcon(icon2)
        self.menuBaud_Rate.setObjectName(_fromUtf8("menuBaud_Rate"))
        self.menuConfigurar = QtGui.QMenu(self.menubar)
        self.menuConfigurar.setTitle(QtGui.QApplication.translate("MainWindow", "Configurar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuConfigurar.setObjectName(_fromUtf8("menuConfigurar"))
        self.menuAbertura = QtGui.QMenu(self.menuConfigurar)
        self.menuAbertura.setTitle(QtGui.QApplication.translate("MainWindow", "Abertura", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAbertura.setObjectName(_fromUtf8("menuAbertura"))
        self.menuTimer = QtGui.QMenu(self.menuConfigurar)
        self.menuTimer.setTitle(QtGui.QApplication.translate("MainWindow", "Timer", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTimer.setObjectName(_fromUtf8("menuTimer"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionConectar = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/1351621501_Check.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConectar.setIcon(icon3)
        self.actionConectar.setText(QtGui.QApplication.translate("MainWindow", "Conectar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConectar.setObjectName(_fromUtf8("actionConectar"))
        self.actionDesconectar = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/1351619288_DeleteRed.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDesconectar.setIcon(icon4)
        self.actionDesconectar.setText(QtGui.QApplication.translate("MainWindow", "Desconectar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionDesconectar.setObjectName(_fromUtf8("actionDesconectar"))
        self.Addr20 = QtGui.QAction(MainWindow)
        self.Addr20.setText(QtGui.QApplication.translate("MainWindow", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.Addr20.setObjectName(_fromUtf8("Addr20"))
        self.Addr21 = QtGui.QAction(MainWindow)
        self.Addr21.setText(QtGui.QApplication.translate("MainWindow", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.Addr21.setObjectName(_fromUtf8("Addr21"))
        self.Addr22 = QtGui.QAction(MainWindow)
        self.Addr22.setText(QtGui.QApplication.translate("MainWindow", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.Addr22.setObjectName(_fromUtf8("Addr22"))
        self.Addr23 = QtGui.QAction(MainWindow)
        self.Addr23.setText(QtGui.QApplication.translate("MainWindow", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.Addr23.setObjectName(_fromUtf8("Addr23"))
        self.Addr24 = QtGui.QAction(MainWindow)
        self.Addr24.setText(QtGui.QApplication.translate("MainWindow", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.Addr24.setObjectName(_fromUtf8("Addr24"))
        self.Port1 = QtGui.QAction(MainWindow)
        self.Port1.setText(QtGui.QApplication.translate("MainWindow", "COM1", None, QtGui.QApplication.UnicodeUTF8))
        self.Port1.setObjectName(_fromUtf8("Port1"))
        self.Port2 = QtGui.QAction(MainWindow)
        self.Port2.setText(QtGui.QApplication.translate("MainWindow", "COM2", None, QtGui.QApplication.UnicodeUTF8))
        self.Port2.setObjectName(_fromUtf8("Port2"))
        self.Port3 = QtGui.QAction(MainWindow)
        self.Port3.setText(QtGui.QApplication.translate("MainWindow", "COM3", None, QtGui.QApplication.UnicodeUTF8))
        self.Port3.setObjectName(_fromUtf8("Port3"))
        self.Port4 = QtGui.QAction(MainWindow)
        self.Port4.setText(QtGui.QApplication.translate("MainWindow", "COM4", None, QtGui.QApplication.UnicodeUTF8))
        self.Port4.setObjectName(_fromUtf8("Port4"))
        self.Port5 = QtGui.QAction(MainWindow)
        self.Port5.setText(QtGui.QApplication.translate("MainWindow", "COM5", None, QtGui.QApplication.UnicodeUTF8))
        self.Port5.setObjectName(_fromUtf8("Port5"))
        self.Port6 = QtGui.QAction(MainWindow)
        self.Port6.setText(QtGui.QApplication.translate("MainWindow", "COM6", None, QtGui.QApplication.UnicodeUTF8))
        self.Port6.setObjectName(_fromUtf8("Port6"))
        self.Port7 = QtGui.QAction(MainWindow)
        self.Port7.setText(QtGui.QApplication.translate("MainWindow", "COM7", None, QtGui.QApplication.UnicodeUTF8))
        self.Port7.setObjectName(_fromUtf8("Port7"))
        self.Port8 = QtGui.QAction(MainWindow)
        self.Port8.setText(QtGui.QApplication.translate("MainWindow", "COM8", None, QtGui.QApplication.UnicodeUTF8))
        self.Port8.setObjectName(_fromUtf8("Port8"))
        self.Port9 = QtGui.QAction(MainWindow)
        self.Port9.setText(QtGui.QApplication.translate("MainWindow", "COM9", None, QtGui.QApplication.UnicodeUTF8))
        self.Port9.setObjectName(_fromUtf8("Port9"))
        self.action300 = QtGui.QAction(MainWindow)
        self.action300.setText(QtGui.QApplication.translate("MainWindow", "300 bps", None, QtGui.QApplication.UnicodeUTF8))
        self.action300.setObjectName(_fromUtf8("action300"))
        self.action600 = QtGui.QAction(MainWindow)
        self.action600.setText(QtGui.QApplication.translate("MainWindow", "600 bps", None, QtGui.QApplication.UnicodeUTF8))
        self.action600.setObjectName(_fromUtf8("action600"))
        self.action1200 = QtGui.QAction(MainWindow)
        self.action1200.setText(QtGui.QApplication.translate("MainWindow", "1200 bps", None, QtGui.QApplication.UnicodeUTF8))
        self.action1200.setObjectName(_fromUtf8("action1200"))
        self.action4800 = QtGui.QAction(MainWindow)
        self.action4800.setText(QtGui.QApplication.translate("MainWindow", "4800 bs", None, QtGui.QApplication.UnicodeUTF8))
        self.action4800.setObjectName(_fromUtf8("action4800"))
        self.action9600 = QtGui.QAction(MainWindow)
        self.action9600.setText(QtGui.QApplication.translate("MainWindow", "9600 bps", None, QtGui.QApplication.UnicodeUTF8))
        self.action9600.setObjectName(_fromUtf8("action9600"))
        self.action19200 = QtGui.QAction(MainWindow)
        self.action19200.setText(QtGui.QApplication.translate("MainWindow", "19200 bps", None, QtGui.QApplication.UnicodeUTF8))
        self.action19200.setObjectName(_fromUtf8("action19200"))
        self.action2400 = QtGui.QAction(MainWindow)
        self.action2400.setText(QtGui.QApplication.translate("MainWindow", "2400 bps", None, QtGui.QApplication.UnicodeUTF8))
        self.action2400.setObjectName(_fromUtf8("action2400"))
        self.Addr25 = QtGui.QAction(MainWindow)
        self.Addr25.setText(QtGui.QApplication.translate("MainWindow", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.Addr25.setObjectName(_fromUtf8("Addr25"))
        self.action166_ms = QtGui.QAction(MainWindow)
        self.action166_ms.setText(QtGui.QApplication.translate("MainWindow", "166 ms (60 Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.action166_ms.setObjectName(_fromUtf8("action166_ms"))
        self.action500_ns = QtGui.QAction(MainWindow)
        self.action500_ns.setText(QtGui.QApplication.translate("MainWindow", "200 ms (50 ~ 400 Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.action500_ns.setObjectName(_fromUtf8("action500_ns"))
        self.action500_ns_Default = QtGui.QAction(MainWindow)
        self.action500_ns_Default.setText(QtGui.QApplication.translate("MainWindow", "500 ns (Default)", None, QtGui.QApplication.UnicodeUTF8))
        self.action500_ns_Default.setObjectName(_fromUtf8("action500_ns_Default"))
        self.action500_ns_Default_2 = QtGui.QAction(MainWindow)
        self.action500_ns_Default_2.setText(QtGui.QApplication.translate("MainWindow", "500 ns (Default)", None, QtGui.QApplication.UnicodeUTF8))
        self.action500_ns_Default_2.setObjectName(_fromUtf8("action500_ns_Default_2"))
        self.action166_ms_2 = QtGui.QAction(MainWindow)
        self.action166_ms_2.setText(QtGui.QApplication.translate("MainWindow", "166 ms (60 Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.action166_ms_2.setObjectName(_fromUtf8("action166_ms_2"))
        self.action200_ms = QtGui.QAction(MainWindow)
        self.action200_ms.setText(QtGui.QApplication.translate("MainWindow", "200 ms (50 ~ 400 Hz)", None, QtGui.QApplication.UnicodeUTF8))
        self.action200_ms.setObjectName(_fromUtf8("action200_ms"))
        self.actionConfigura = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/configure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfigura.setIcon(icon5)
        self.actionConfigura.setText(QtGui.QApplication.translate("MainWindow", "Configura", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfigura.setObjectName(_fromUtf8("actionConfigura"))
        self.action1_segundo = QtGui.QAction(MainWindow)
        self.action1_segundo.setText(QtGui.QApplication.translate("MainWindow", "1 segundo", None, QtGui.QApplication.UnicodeUTF8))
        self.action1_segundo.setObjectName(_fromUtf8("action1_segundo"))
        self.action2_segundos = QtGui.QAction(MainWindow)
        self.action2_segundos.setText(QtGui.QApplication.translate("MainWindow", "2 segundos", None, QtGui.QApplication.UnicodeUTF8))
        self.action2_segundos.setObjectName(_fromUtf8("action2_segundos"))
        self.action3_segundos = QtGui.QAction(MainWindow)
        self.action3_segundos.setText(QtGui.QApplication.translate("MainWindow", "3 segundos", None, QtGui.QApplication.UnicodeUTF8))
        self.action3_segundos.setObjectName(_fromUtf8("action3_segundos"))
        self.action4_segundos = QtGui.QAction(MainWindow)
        self.action4_segundos.setText(QtGui.QApplication.translate("MainWindow", "4 segundos", None, QtGui.QApplication.UnicodeUTF8))
        self.action4_segundos.setObjectName(_fromUtf8("action4_segundos"))
        self.menuAddress.addAction(self.Addr20)
        self.menuAddress.addAction(self.Addr21)
        self.menuAddress.addAction(self.Addr22)
        self.menuAddress.addAction(self.Addr23)
        self.menuAddress.addAction(self.Addr24)
        self.menuAddress.addAction(self.Addr25)
        self.menuPort.addAction(self.Port1)
        self.menuPort.addAction(self.Port2)
        self.menuPort.addAction(self.Port3)
        self.menuPort.addAction(self.Port4)
        self.menuPort.addAction(self.Port5)
        self.menuPort.addAction(self.Port6)
        self.menuPort.addAction(self.Port7)
        self.menuPort.addAction(self.Port8)
        self.menuPort.addAction(self.Port9)
        self.menuBaud_Rate.addAction(self.action300)
        self.menuBaud_Rate.addAction(self.action600)
        self.menuBaud_Rate.addAction(self.action1200)
        self.menuBaud_Rate.addAction(self.action2400)
        self.menuBaud_Rate.addAction(self.action4800)
        self.menuBaud_Rate.addAction(self.action9600)
        self.menuBaud_Rate.addAction(self.action19200)
        self.menuConexao.addAction(self.menuAddress.menuAction())
        self.menuConexao.addAction(self.menuPort.menuAction())
        self.menuConexao.addAction(self.menuBaud_Rate.menuAction())
        self.menuConexao.addAction(self.actionConectar)
        self.menuConexao.addAction(self.actionDesconectar)
        self.menuAbertura.addAction(self.action500_ns_Default_2)
        self.menuAbertura.addAction(self.action166_ms_2)
        self.menuAbertura.addAction(self.action200_ms)
        self.menuTimer.addAction(self.action1_segundo)
        self.menuTimer.addAction(self.action2_segundos)
        self.menuTimer.addAction(self.action3_segundos)
        self.menuTimer.addAction(self.action4_segundos)
        self.menuConfigurar.addAction(self.menuAbertura.menuAction())
        self.menuConfigurar.addAction(self.menuTimer.menuAction())
        self.menuConfigurar.addAction(self.actionConfigura)
        self.menubar.addAction(self.menuConexao.menuAction())
        self.menubar.addAction(self.menuConfigurar.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Leitura", None, QtGui.QApplication.UnicodeUTF8))

