# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface4.ui'
#
# Created: Thu Dec  4 14:46:50 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(819, 725)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 821, 691))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(22, 22))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.pb_Conectar = QtGui.QPushButton(self.tab)
        self.pb_Conectar.setGeometry(QtCore.QRect(100, 420, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_Conectar.setFont(font)
        self.pb_Conectar.setText(QtGui.QApplication.translate("MainWindow", " Conectar", None, QtGui.QApplication.UnicodeUTF8))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/Power_On.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Conectar.setIcon(icon)
        self.pb_Conectar.setIconSize(QtCore.QSize(23, 23))
        self.pb_Conectar.setObjectName(_fromUtf8("pb_Conectar"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(40, 190, 281, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Comunicação", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.ptdriver_label = QtGui.QLabel(self.groupBox)
        self.ptdriver_label.setGeometry(QtCore.QRect(10, 50, 121, 31))
        self.ptdriver_label.setText(QtGui.QApplication.translate("MainWindow", "Porta Driver:", None, QtGui.QApplication.UnicodeUTF8))
        self.ptdriver_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ptdriver_label.setObjectName(_fromUtf8("ptdriver_label"))
        self.cb_portadriver = QtGui.QComboBox(self.groupBox)
        self.cb_portadriver.setGeometry(QtCore.QRect(160, 50, 91, 31))
        self.cb_portadriver.setObjectName(_fromUtf8("cb_portadriver"))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(0, QtGui.QApplication.translate("MainWindow", "COM 1", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(1, QtGui.QApplication.translate("MainWindow", "COM 2", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(2, QtGui.QApplication.translate("MainWindow", "COM 3", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(3, QtGui.QApplication.translate("MainWindow", "COM 4", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(4, QtGui.QApplication.translate("MainWindow", "COM 5", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(5, QtGui.QApplication.translate("MainWindow", "COM 6", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(6, QtGui.QApplication.translate("MainWindow", "COM 7", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(7, QtGui.QApplication.translate("MainWindow", "COM 8", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(8, QtGui.QApplication.translate("MainWindow", "COM 9", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(9, QtGui.QApplication.translate("MainWindow", "COM 10", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_portadriver.addItem(_fromUtf8(""))
        self.cb_portadriver.setItemText(10, QtGui.QApplication.translate("MainWindow", "COM 11", None, QtGui.QApplication.UnicodeUTF8))
        self.bdrate_label = QtGui.QLabel(self.groupBox)
        self.bdrate_label.setGeometry(QtCore.QRect(10, 100, 121, 31))
        self.bdrate_label.setText(QtGui.QApplication.translate("MainWindow", "Baud Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.bdrate_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.bdrate_label.setObjectName(_fromUtf8("bdrate_label"))
        self.cb_baudrate = QtGui.QComboBox(self.groupBox)
        self.cb_baudrate.setGeometry(QtCore.QRect(160, 100, 91, 31))
        self.cb_baudrate.setObjectName(_fromUtf8("cb_baudrate"))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.setItemText(0, QtGui.QApplication.translate("MainWindow", "300", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.setItemText(1, QtGui.QApplication.translate("MainWindow", "600", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.setItemText(2, QtGui.QApplication.translate("MainWindow", "1200", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.setItemText(3, QtGui.QApplication.translate("MainWindow", "2400", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.setItemText(4, QtGui.QApplication.translate("MainWindow", "4800", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.setItemText(5, QtGui.QApplication.translate("MainWindow", "9600", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_baudrate.addItem(_fromUtf8(""))
        self.cb_baudrate.setItemText(6, QtGui.QApplication.translate("MainWindow", "19200", None, QtGui.QApplication.UnicodeUTF8))
        self.Titulo = QtGui.QLabel(self.tab)
        self.Titulo.setGeometry(QtCore.QRect(120, 50, 551, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Leelawadee"))
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.Titulo.setFont(font)
        self.Titulo.setText(QtGui.QApplication.translate("MainWindow", "NMR Controller Interface", None, QtGui.QApplication.UnicodeUTF8))
        self.Titulo.setObjectName(_fromUtf8("Titulo"))
        self.LNLS_logo = QtGui.QLabel(self.tab)
        self.LNLS_logo.setGeometry(QtCore.QRect(400, 200, 331, 191))
        self.LNLS_logo.setText(_fromUtf8(""))
        self.LNLS_logo.setPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/lnls sirius logo.png")))
        self.LNLS_logo.setScaledContents(True)
        self.LNLS_logo.setObjectName(_fromUtf8("LNLS_logo"))
        self.CNPEM_logo = QtGui.QLabel(self.tab)
        self.CNPEM_logo.setGeometry(QtCore.QRect(400, 400, 331, 191))
        self.CNPEM_logo.setText(_fromUtf8(""))
        self.CNPEM_logo.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Imagens/logoCNPEM2.qrc.png")))
        self.CNPEM_logo.setScaledContents(True)
        self.CNPEM_logo.setObjectName(_fromUtf8("CNPEM_logo"))
        self.pb_Desconectar = QtGui.QPushButton(self.tab)
        self.pb_Desconectar.setGeometry(QtCore.QRect(100, 480, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_Desconectar.setFont(font)
        self.pb_Desconectar.setText(QtGui.QApplication.translate("MainWindow", " Desconectar", None, QtGui.QApplication.UnicodeUTF8))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/Power_Off.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_Desconectar.setIcon(icon1)
        self.pb_Desconectar.setIconSize(QtCore.QSize(23, 23))
        self.pb_Desconectar.setObjectName(_fromUtf8("pb_Desconectar"))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/cable.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon2, _fromUtf8(""))
        self.tab_Aquisicao = QtGui.QWidget()
        self.tab_Aquisicao.setObjectName(_fromUtf8("tab_Aquisicao"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_Aquisicao)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 10, 771, 291))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setTitle(QtGui.QApplication.translate("MainWindow", "Painel de Controle", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_8 = QtGui.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(20, 40, 261, 21))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Frequência para início da varredura:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.freq_sweep = QtGui.QLineEdit(self.groupBox_5)
        self.freq_sweep.setGeometry(QtCore.QRect(280, 40, 51, 21))
        self.freq_sweep.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Frequência inicial para inicio da varredura. Nesta etapa, será realizada a leitura da frequência e posteriormente incremento na variação da frequência final.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_sweep.setText(QtGui.QApplication.translate("MainWindow", "1000", None, QtGui.QApplication.UnicodeUTF8))
        self.freq_sweep.setObjectName(_fromUtf8("freq_sweep"))
        self.label_18 = QtGui.QLabel(self.groupBox_5)
        self.label_18.setGeometry(QtCore.QRect(340, 40, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setText(QtGui.QApplication.translate("MainWindow", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.pb_configura = QtGui.QPushButton(self.groupBox_5)
        self.pb_configura.setGeometry(QtCore.QRect(320, 250, 131, 31))
        self.pb_configura.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Roda a configuração setada.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.pb_configura.setText(QtGui.QApplication.translate("MainWindow", "Configura", None, QtGui.QApplication.UnicodeUTF8))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/engine.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pb_configura.setIcon(icon3)
        self.pb_configura.setIconSize(QtCore.QSize(23, 23))
        self.pb_configura.setObjectName(_fromUtf8("pb_configura"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(400, 20, 351, 61))
        self.groupBox_6.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Permite-se alterar a inclinçao da pesquisa. O modo &quot;Alta&quot; corresponde à 9 segundos para escanear o campo. No modo &quot;Normal&quot; 18 segundos e no modo &quot;Baixa&quot; (24 segundos).</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("MainWindow", "Velocidade de aquisição", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.rb_High = QtGui.QRadioButton(self.groupBox_6)
        self.rb_High.setGeometry(QtCore.QRect(190, 30, 71, 21))
        self.rb_High.setText(QtGui.QApplication.translate("MainWindow", "Alta", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_High.setObjectName(_fromUtf8("rb_High"))
        self.rb_Low = QtGui.QRadioButton(self.groupBox_6)
        self.rb_Low.setGeometry(QtCore.QRect(30, 30, 71, 16))
        self.rb_Low.setText(QtGui.QApplication.translate("MainWindow", "Baixa", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Low.setObjectName(_fromUtf8("rb_Low"))
        self.rb_Normal = QtGui.QRadioButton(self.groupBox_6)
        self.rb_Normal.setGeometry(QtCore.QRect(100, 30, 71, 16))
        self.rb_Normal.setText(QtGui.QApplication.translate("MainWindow", "Normal ", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_Normal.setChecked(True)
        self.rb_Normal.setObjectName(_fromUtf8("rb_Normal"))
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 90, 351, 151))
        self.groupBox_9.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Seleciona o tipo de prova utilizada na varredura. Única: Apenas uma ponta de prova. Várias: Varredura com mais de uma ponta de prova.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("MainWindow", "Pontas de prova", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.cb_Channel_fim = QtGui.QComboBox(self.groupBox_9)
        self.cb_Channel_fim.setGeometry(QtCore.QRect(280, 90, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_Channel_fim.setFont(font)
        self.cb_Channel_fim.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Seleciona o canal do Multiplexador</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.setObjectName(_fromUtf8("cb_Channel_fim"))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(1, QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(2, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(3, QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(4, QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(5, QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(6, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_fim.addItem(_fromUtf8(""))
        self.cb_Channel_fim.setItemText(7, QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17 = QtGui.QLabel(self.groupBox_9)
        self.label_17.setGeometry(QtCore.QRect(200, 90, 51, 21))
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "Final:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.label_13 = QtGui.QLabel(self.groupBox_9)
        self.label_13.setGeometry(QtCore.QRect(30, 70, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "Canal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_9)
        self.label_14.setGeometry(QtCore.QRect(200, 60, 61, 21))
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "Inicial:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.cb_Channel_2 = QtGui.QComboBox(self.groupBox_9)
        self.cb_Channel_2.setGeometry(QtCore.QRect(100, 70, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_Channel_2.setFont(font)
        self.cb_Channel_2.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Seleciona o canal do Multiplexador</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.setObjectName(_fromUtf8("cb_Channel_2"))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(1, QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(2, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(3, QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(4, QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(5, QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(6, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_2.addItem(_fromUtf8(""))
        self.cb_Channel_2.setItemText(7, QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini = QtGui.QComboBox(self.groupBox_9)
        self.cb_Channel_ini.setGeometry(QtCore.QRect(280, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_Channel_ini.setFont(font)
        self.cb_Channel_ini.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Seleciona o canal do Multiplexador</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.setObjectName(_fromUtf8("cb_Channel_ini"))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(0, QtGui.QApplication.translate("MainWindow", "A", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(1, QtGui.QApplication.translate("MainWindow", "B", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(2, QtGui.QApplication.translate("MainWindow", "C", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(3, QtGui.QApplication.translate("MainWindow", "D", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(4, QtGui.QApplication.translate("MainWindow", "E", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(5, QtGui.QApplication.translate("MainWindow", "F", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(6, QtGui.QApplication.translate("MainWindow", "G", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Channel_ini.addItem(_fromUtf8(""))
        self.cb_Channel_ini.setItemText(7, QtGui.QApplication.translate("MainWindow", "H", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_sgl_probe = QtGui.QRadioButton(self.groupBox_9)
        self.rb_sgl_probe.setGeometry(QtCore.QRect(50, 30, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rb_sgl_probe.setFont(font)
        self.rb_sgl_probe.setText(QtGui.QApplication.translate("MainWindow", "Única", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_sgl_probe.setChecked(True)
        self.rb_sgl_probe.setObjectName(_fromUtf8("rb_sgl_probe"))
        self.rb_svr_probe = QtGui.QRadioButton(self.groupBox_9)
        self.rb_svr_probe.setGeometry(QtCore.QRect(220, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.rb_svr_probe.setFont(font)
        self.rb_svr_probe.setText(QtGui.QApplication.translate("MainWindow", "Várias", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_svr_probe.setObjectName(_fromUtf8("rb_svr_probe"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 90, 351, 151))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Configuração", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Aqui escolhe-se qual será o tipo de varredura da frequência. No modo Automático, o PT-2025 varre a radio frequencia sobre todo o range do potenciômetro de ajuste fino (FINE). O que representa uma variação de +/- 5% da frequência atual selecionada no potênciometro de ajuste grosso (COARSE).</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setWhatsThis(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Aqui escolhe-se qual será o tipo de varredura da frequência. No modo Automático, o PT-2025 varre a radio frequencia sobre todo o rande do potenciômetro de ajuste fino (FINE). O que representa uma variação de +/- 5% da frequência atual selecionada no potênciometro de ajuste grosso (COARSE).</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Varredura da frequência:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cb_Aquisition = QtGui.QComboBox(self.groupBox_2)
        self.cb_Aquisition.setGeometry(QtCore.QRect(230, 30, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_Aquisition.setFont(font)
        self.cb_Aquisition.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Aqui escolhe-se qual será o tipo de varredura da frequência. No modo Automático, o PT-2025 varre a rádio frequência sobre todo o range do potenciômetro de ajuste fino (FINE) que permanece desabilitado no modo Automático. Isso representa uma variação de +/- 5% da frequência atual selecionada pelo potênciometro de ajuste grosso (COARSE). </span></p>\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">No modo Manual, este ajuste é feito manualmente tomando como referência os leds TOO LO indicando que o ajuste grosso de frequência está abaixo do valor esperado e TOO HI para valores acima.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Aquisition.setObjectName(_fromUtf8("cb_Aquisition"))
        self.cb_Aquisition.addItem(_fromUtf8(""))
        self.cb_Aquisition.setItemText(0, QtGui.QApplication.translate("MainWindow", "Manual", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Aquisition.addItem(_fromUtf8(""))
        self.cb_Aquisition.setItemText(1, QtGui.QApplication.translate("MainWindow", "Auto", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_FieldSense = QtGui.QComboBox(self.groupBox_2)
        self.cb_FieldSense.setGeometry(QtCore.QRect(230, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_FieldSense.setFont(font)
        self.cb_FieldSense.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Determine a sensibilidade do campo a ser medido com relação à orientação da sonda.</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_FieldSense.setObjectName(_fromUtf8("cb_FieldSense"))
        self.cb_FieldSense.addItem(_fromUtf8(""))
        self.cb_FieldSense.setItemText(0, QtGui.QApplication.translate("MainWindow", "Negativo", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_FieldSense.addItem(_fromUtf8(""))
        self.cb_FieldSense.setItemText(1, QtGui.QApplication.translate("MainWindow", "Positivo", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(30, 60, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Orientação do Campo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(30, 89, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Display:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cb_Display = QtGui.QComboBox(self.groupBox_2)
        self.cb_Display.setGeometry(QtCore.QRect(230, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_Display.setFont(font)
        self.cb_Display.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Determina se o valor mostrado no display será dado em Tesla (valor do campo) ou em MHz (valor da frequência setada).</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Display.setObjectName(_fromUtf8("cb_Display"))
        self.cb_Display.addItem(_fromUtf8(""))
        self.cb_Display.setItemText(0, QtGui.QApplication.translate("MainWindow", "MHz", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Display.addItem(_fromUtf8(""))
        self.cb_Display.setItemText(1, QtGui.QApplication.translate("MainWindow", "Tesla", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(30, 120, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "Display Fast:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.cb_Display_fast = QtGui.QComboBox(self.groupBox_2)
        self.cb_Display_fast.setGeometry(QtCore.QRect(230, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cb_Display_fast.setFont(font)
        self.cb_Display_fast.setToolTip(QtGui.QApplication.translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Determina se o valor mostrado no display será dado em Tesla (valor do campo) ou em MHz (valor da frequência setada).</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Display_fast.setObjectName(_fromUtf8("cb_Display_fast"))
        self.cb_Display_fast.addItem(_fromUtf8(""))
        self.cb_Display_fast.setItemText(0, QtGui.QApplication.translate("MainWindow", "OFF", None, QtGui.QApplication.UnicodeUTF8))
        self.cb_Display_fast.addItem(_fromUtf8(""))
        self.cb_Display_fast.setItemText(1, QtGui.QApplication.translate("MainWindow", "ON", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7 = QtGui.QGroupBox(self.tab_Aquisicao)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 310, 771, 341))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("MainWindow", "Varredura", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.dataready = QtGui.QLineEdit(self.groupBox_7)
        self.dataready.setGeometry(QtCore.QRect(240, 30, 91, 21))
        self.dataready.setObjectName(_fromUtf8("dataready"))
        self.label_15 = QtGui.QLabel(self.groupBox_7)
        self.label_15.setGeometry(QtCore.QRect(30, 30, 181, 21))
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "Fim do ciclo de medida:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setGeometry(QtCore.QRect(30, 70, 141, 21))
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "Sinal Observado:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.signalseen = QtGui.QLineEdit(self.groupBox_7)
        self.signalseen.setGeometry(QtCore.QRect(240, 70, 91, 21))
        self.signalseen.setObjectName(_fromUtf8("signalseen"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(50, 230, 251, 91))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("MainWindow", "Field Search", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.tooloRed = QtGui.QLabel(self.groupBox_8)
        self.tooloRed.setGeometry(QtCore.QRect(150, 30, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tooloRed.setFont(font)
        self.tooloRed.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.tooloRed.setText(QtGui.QApplication.translate("MainWindow", "  TOO LO", None, QtGui.QApplication.UnicodeUTF8))
        self.tooloRed.setObjectName(_fromUtf8("tooloRed"))
        self.tooloGreen = QtGui.QLabel(self.groupBox_8)
        self.tooloGreen.setGeometry(QtCore.QRect(150, 30, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tooloGreen.setFont(font)
        self.tooloGreen.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 255, 0);"))
        self.tooloGreen.setText(QtGui.QApplication.translate("MainWindow", "  TOO LO", None, QtGui.QApplication.UnicodeUTF8))
        self.tooloGreen.setObjectName(_fromUtf8("tooloGreen"))
        self.toohiRed = QtGui.QLabel(self.groupBox_8)
        self.toohiRed.setGeometry(QtCore.QRect(20, 30, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toohiRed.setFont(font)
        self.toohiRed.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.toohiRed.setText(QtGui.QApplication.translate("MainWindow", "  TOO HI", None, QtGui.QApplication.UnicodeUTF8))
        self.toohiRed.setObjectName(_fromUtf8("toohiRed"))
        self.toohiGreen = QtGui.QLabel(self.groupBox_8)
        self.toohiGreen.setGeometry(QtCore.QRect(20, 30, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.toohiGreen.setFont(font)
        self.toohiGreen.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 255, 0);"))
        self.toohiGreen.setText(QtGui.QApplication.translate("MainWindow", "  TOO HI", None, QtGui.QApplication.UnicodeUTF8))
        self.toohiGreen.setObjectName(_fromUtf8("toohiGreen"))
        self.Signal_State = QtGui.QLineEdit(self.groupBox_7)
        self.Signal_State.setGeometry(QtCore.QRect(240, 120, 91, 21))
        self.Signal_State.setText(_fromUtf8(""))
        self.Signal_State.setObjectName(_fromUtf8("Signal_State"))
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        self.label_21.setGeometry(QtCore.QRect(30, 120, 191, 21))
        self.label_21.setText(QtGui.QApplication.translate("MainWindow", "Presença de sinal no NMR:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lcd_Freq_2 = QtGui.QLCDNumber(self.groupBox_7)
        self.lcd_Freq_2.setGeometry(QtCore.QRect(430, 130, 301, 51))
        self.lcd_Freq_2.setNumDigits(7)
        self.lcd_Freq_2.setObjectName(_fromUtf8("lcd_Freq_2"))
        self.searchmd = QtGui.QLineEdit(self.groupBox_7)
        self.searchmd.setGeometry(QtCore.QRect(480, 300, 71, 21))
        self.searchmd.setObjectName(_fromUtf8("searchmd"))
        self.label_24 = QtGui.QLabel(self.groupBox_7)
        self.label_24.setGeometry(QtCore.QRect(380, 260, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setText(QtGui.QApplication.translate("MainWindow", "Campo +/-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_28 = QtGui.QLabel(self.groupBox_7)
        self.label_28.setGeometry(QtCore.QRect(570, 240, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_28.setFont(font)
        self.label_28.setText(QtGui.QApplication.translate("MainWindow", "Multiplexador:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.multiplex = QtGui.QLineEdit(self.groupBox_7)
        self.multiplex.setGeometry(QtCore.QRect(670, 240, 71, 21))
        self.multiplex.setObjectName(_fromUtf8("multiplex"))
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        self.label_29.setGeometry(QtCore.QRect(570, 280, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_29.setFont(font)
        self.label_29.setText(QtGui.QApplication.translate("MainWindow", "Display Fast:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_25 = QtGui.QLabel(self.groupBox_7)
        self.label_25.setGeometry(QtCore.QRect(530, 80, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setText(QtGui.QApplication.translate("MainWindow", "Campo (Tesla)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_7)
        self.label_26.setGeometry(QtCore.QRect(520, 180, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setText(QtGui.QApplication.translate("MainWindow", "Frequência (MHz)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.fastRead = QtGui.QLineEdit(self.groupBox_7)
        self.fastRead.setGeometry(QtCore.QRect(670, 280, 71, 21))
        self.fastRead.setObjectName(_fromUtf8("fastRead"))
        self.lcd_Campo_2 = QtGui.QLCDNumber(self.groupBox_7)
        self.lcd_Campo_2.setGeometry(QtCore.QRect(430, 30, 301, 51))
        self.lcd_Campo_2.setNumDigits(7)
        self.lcd_Campo_2.setDigitCount(7)
        self.lcd_Campo_2.setObjectName(_fromUtf8("lcd_Campo_2"))
        self.auto_manu = QtGui.QLineEdit(self.groupBox_7)
        self.auto_manu.setGeometry(QtCore.QRect(480, 220, 71, 21))
        self.auto_manu.setObjectName(_fromUtf8("auto_manu"))
        self.Posit_Negat = QtGui.QLineEdit(self.groupBox_7)
        self.Posit_Negat.setGeometry(QtCore.QRect(480, 260, 71, 21))
        self.Posit_Negat.setObjectName(_fromUtf8("Posit_Negat"))
        self.label_27 = QtGui.QLabel(self.groupBox_7)
        self.label_27.setGeometry(QtCore.QRect(380, 300, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_27.setFont(font)
        self.label_27.setText(QtGui.QApplication.translate("MainWindow", "Search mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_23 = QtGui.QLabel(self.groupBox_7)
        self.label_23.setGeometry(QtCore.QRect(380, 220, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setText(QtGui.QApplication.translate("MainWindow", "Varredura:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.line = QtGui.QFrame(self.groupBox_7)
        self.line.setGeometry(QtCore.QRect(350, 20, 20, 311))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.NMR_lock_gree = QtGui.QLabel(self.groupBox_7)
        self.NMR_lock_gree.setGeometry(QtCore.QRect(120, 160, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NMR_lock_gree.setFont(font)
        self.NMR_lock_gree.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"background-color: rgb(0, 255, 0);"))
        self.NMR_lock_gree.setText(QtGui.QApplication.translate("MainWindow", "  NMR LOCK", None, QtGui.QApplication.UnicodeUTF8))
        self.NMR_lock_gree.setObjectName(_fromUtf8("NMR_lock_gree"))
        self.NMR_lock_tran = QtGui.QLabel(self.groupBox_7)
        self.NMR_lock_tran.setGeometry(QtCore.QRect(120, 160, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NMR_lock_tran.setFont(font)
        self.NMR_lock_tran.setStyleSheet(_fromUtf8(""))
        self.NMR_lock_tran.setText(QtGui.QApplication.translate("MainWindow", "  NMR LOCK", None, QtGui.QApplication.UnicodeUTF8))
        self.NMR_lock_tran.setObjectName(_fromUtf8("NMR_lock_tran"))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../bobinona/imagens/regua.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_Aquisicao, icon4, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 819, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.cb_portadriver.setCurrentIndex(4)
        self.cb_baudrate.setCurrentIndex(6)
        self.cb_Channel_fim.setCurrentIndex(3)
        self.cb_Channel_2.setCurrentIndex(0)
        self.cb_Channel_ini.setCurrentIndex(1)
        self.cb_Aquisition.setCurrentIndex(1)
        self.cb_FieldSense.setCurrentIndex(0)
        self.cb_Display_fast.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "Conexão", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Aquisicao), QtGui.QApplication.translate("MainWindow", "Aquisição", None, QtGui.QApplication.UnicodeUTF8))

